graph LR
    A[nginx] --80:3001--> B[Gateway ]
    B--/project1 : service1:80-->C[service 1]
    B--/project2 : service2:80-->D[service 2]
    B--/project3 : service3:80-->E[service 3]

    Other[其他] -.不可访问.-> C